name: Master Build

on:
  push:
    branches: [ "ZEOP-3168" ]

env:
  BACKEND_REPO: 'SmartBear/zephyr-enterprise-test-management-plugin'
  BACKEND_BRANCH: 'main'

jobs:
  build:
    name: Run Build
    runs-on: zephyr-enterprise-test-management-plugin
    permissions:
      id-token: write
      contents: write

    steps:
  
    - name: Checkout BackEnd Code
      uses: actions/checkout@v2
      with:
        repository: ${{ env.BACKEND_REPO }}
        ref: ${{ env.BACKEND_BRANCH }}
        fetch-depth: 0
        
    - name: Cache Maven Packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2     
        
    - name: Build with Maven
      run:  |
       /opt/apache-maven-3.8.8/bin/mvn clean package -Dmaven.test.skip=true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
        role-session-name: ${{ secrets.ROLE_SESSION_NAME }}
        aws-region: us-east-2

    - name: Copy build files to S3
      run: |
        aws s3 cp target/zephyr-enterprise-test-management*.hpi s3://ze-test-management-plugin-builds/GithubBuilds/Release/${{ env.BACKEND_BRANCH }}_${{ github.run_number }}.hpi